# Generated by Django 3.0.1 on 2020-02-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'ordering': ['index'], 'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='img',
            field=models.ImageField(default='default/banner.png', upload_to='banners/%Y/%m/%d', verbose_name='轮播图片'),
        ),
        migrations.AlterModelTable(
            name='bannermodel',
            table='geng_banner',
        ),
    ]
