# Generated by Django 3.0.1 on 2020-02-07 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200207_1839'),
        ('banner', '0002_auto_20200207_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.CourseModel'),
        ),
    ]
