# Generated by Django 3.0.1 on 2020-02-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20200207_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermodel',
            name='desc',
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='sub_title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='副标题'),
        ),
    ]
