# Generated by Django 3.0.1 on 2020-02-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0016_courselistmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('sub_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='副标题')),
                ('index', models.PositiveSmallIntegerField(default=1, verbose_name='轮播图序号')),
                ('url', models.URLField(default='/', verbose_name='跳转链接')),
                ('img', models.ImageField(default='default/banner.png', upload_to='banners/%Y/%m/%d', verbose_name='图片（建议尺寸960*425）')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'geng_banner',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='BannerCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='导航项名称(5~7个)')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='显示顺序')),
                ('category', models.ManyToManyField(blank=True, null=True, to='course.CourseCategoryModel', verbose_name='关联课程分类(显示两个)')),
            ],
            options={
                'verbose_name': '导航栏左侧分类',
                'verbose_name_plural': '导航栏左侧分类',
                'ordering': ['index'],
            },
        ),
    ]
