# Generated by Django 3.0.1 on 2020-02-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_courselistmodel'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercategorymodel',
            name='category',
            field=models.ManyToManyField(to='course.CourseCategoryModel', verbose_name='关联课程分类(显示两个)'),
        ),
    ]
