# Generated by Django 3.0.1 on 2020-02-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_delete_courselistmodel'),
        ('home', '0002_auto_20200209_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannercategorymodel',
            options={'ordering': ['index'], 'verbose_name': '轮播图左侧导航', 'verbose_name_plural': '轮播图左侧导航'},
        ),
        migrations.CreateModel(
            name='CourseListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='列表名称')),
                ('ordering', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('courses', models.ManyToManyField(to='course.CourseModel', verbose_name='所有课程')),
            ],
            options={
                'verbose_name': '课程列表',
                'verbose_name_plural': '课程列表',
                'ordering': ['ordering'],
            },
        ),
    ]
