# Generated by Django 3.0.1 on 2020-02-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='分类名')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='分类别名')),
                ('index', models.PositiveSmallIntegerField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类')], default=1, verbose_name='分类级别')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.CourseCategoryModel', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'geng_course_category',
                'unique_together': {('title', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OrgModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机构名称')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
                'db_table': 'geng_org',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='讲师名称')),
                ('nick_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='讲师昵称')),
                ('avatar', models.ImageField(default='default/avatar.png', upload_to='avatars/%Y/%m/%d', verbose_name='头像')),
                ('desc', models.TextField(verbose_name='讲师介绍')),
                ('org', models.ManyToManyField(to='course.OrgModel', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
                'db_table': 'geng_teacher',
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('sub_title', models.CharField(max_length=32, verbose_name='副标题')),
                ('desc', models.TextField(verbose_name='描述')),
                ('price', models.CharField(default='免费', max_length=11, verbose_name='价格')),
                ('has_activity_price', models.BooleanField(default=False, verbose_name='是否有活动价格')),
                ('activity_price', models.CharField(default='免费', max_length=11, verbose_name='活动价格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.CourseCategoryModel', verbose_name='课程类别')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'geng_course',
            },
        ),
    ]
