# Generated by Django 3.0.1 on 2020-02-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='课程链接'),
        ),
    ]
