# Generated by Django 3.0.1 on 2020-02-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='avatar',
            field=models.ImageField(default='default/avatar.png', upload_to='avatars/%Y/%m/%d', verbose_name='头像'),
        ),
        migrations.AlterModelTable(
            name='coursemodel',
            table='geng_course',
        ),
        migrations.AlterModelTable(
            name='orgmodel',
            table='geng_org',
        ),
        migrations.AlterModelTable(
            name='teachermodel',
            table='geng_teacher',
        ),
    ]
