# Generated by Django 3.0.1 on 2020-02-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nav',
            new_name='BannerNav',
        ),
    ]
