# Generated by Django 3.0.1 on 2020-02-08 19:21

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursemodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterLessonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='最新课时', max_length=32, verbose_name='课时标题')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='课时号')),
                ('joined_item', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '章节课时',
                'verbose_name_plural': '章节课时',
                'db_table': 'geng_course_chapter_lesson',
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='h5_desc',
            field=models.TextField(blank=True, null=True, verbose_name='html描述'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='has_chapter',
            field=models.BooleanField(default=True, verbose_name='是否具有章节'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='视频链接(课程只有唯一视频时启用)'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='sub_title',
            field=models.CharField(blank=course.models.TeacherModel, max_length=32, null=True, verbose_name='副标题'),
        ),
        migrations.CreateModel(
            name='ChapterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='最新章节', max_length=32, verbose_name='章节名称')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='章节数量')),
                ('joined_time', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.ChapterLessonModel', verbose_name='课时')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'db_table': 'geng_course_chapter',
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.ChapterModel', verbose_name='课程的所有章节'),
        ),
    ]
