# Generated by Django 3.0.1 on 2020-02-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200210_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='course.Teacher', verbose_name='讲师'),
        ),
    ]
