# Generated by Django 3.0.1 on 2020-02-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200208_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='has_chapter',
            field=models.BooleanField(default=False, verbose_name='是否具有章节'),
        ),
    ]
