# Generated by Django 3.0.1 on 2020-02-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200211_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_img',
            field=models.ImageField(upload_to='course/cover/%Y/%m/%d', verbose_name='课程封面'),
        ),
    ]
