# Generated by Django 3.0.1 on 2020-02-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200208_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='index',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='章节序号'),
        ),
    ]
