# Generated by Django 3.0.1 on 2020-02-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200211_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='chapter',
        ),
        migrations.AddField(
            model_name='course',
            name='chapter',
            field=models.ManyToManyField(blank=True, to='course.Chapter', verbose_name='课程的所有章节'),
        ),
    ]
