# Generated by Django 3.0.1 on 2020-02-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200208_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='title',
            field=models.CharField(default='最新章节', max_length=32, unique=True, verbose_name='章节名称'),
        ),
    ]
