# Generated by Django 3.0.1 on 2020-02-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200221_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.URLField(default='https://mov.bn.netease.com/open-movie/nos/mp4/2018/11/27/ZE0MHK6MQ_sd.mp4', verbose_name='视频链接'),
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='lesson',
        ),
        migrations.AddField(
            model_name='chapter',
            name='lesson',
            field=models.ManyToManyField(blank=True, to='course.Lesson', verbose_name='课时'),
        ),
    ]
