# Generated by Django 3.0.1 on 2020-02-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_coursemodel_cover_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemodel',
            unique_together={('title', 'sub_title')},
        ),
    ]
