# Generated by Django 3.0.1 on 2020-02-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20200208_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.TeacherModel', verbose_name='讲师'),
        ),
    ]
