# Generated by Django 3.0.1 on 2020-02-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20200208_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='标题'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemodel',
            unique_together=set(),
        ),
    ]
