# Generated by Django 3.0.1 on 2020-02-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20200208_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='列表名称')),
                ('ordering', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('courses', models.ManyToManyField(to='course.CourseModel', verbose_name='所有课程')),
            ],
            options={
                'verbose_name': '课程列表',
                'verbose_name_plural': '课程列表',
                'ordering': ['ordering'],
            },
        ),
    ]
