# Generated by Django 3.0.1 on 2020-02-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_courselistmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseListModel',
        ),
    ]
